# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestA2TestSuite():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_opencartA2(self):
        self.driver.get("https://demo.opencart.com.gr/")
        self.driver.set_window_size(1550, 838)
        print("pagetitle")
        assert self.driver.title == "Your Store"
        self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
        assert self.driver.title == "Mac"
        element = self.driver.find_element(By.ID, "grid-view")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "input-sort").click()
        dropdown = self.driver.find_element(By.ID, "input-sort")
        dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#input-sort > option:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".image .img-responsive").click()
        self.driver.find_element(By.ID, "button-cart").click()
        self.driver.find_element(By.ID, "cart-total").click()
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > strong").click()
        self.driver.find_element(By.NAME, "search").click()
        self.driver.find_element(By.NAME, "search").send_keys("Mobile")
        self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, "p > .checkbox-inline").click()
        self.driver.find_element(By.ID, "button-search").click()
        self.driver.close()

    def test_opencartA21(self):
        self.driver.get("https://demo.opencart.com.gr/")
        self.driver.set_window_size(1550, 838)
        print("pagetitle")
        assert self.driver.title == "Your Store"
        self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()
        assert self.driver.title == "Mac"
        element = self.driver.find_element(By.ID, "grid-view")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "input-sort").click()
        dropdown = self.driver.find_element(By.ID, "input-sort")
        dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#input-sort > option:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".image .img-responsive").click()
        self.driver.find_element(By.ID, "button-cart").click()
        self.driver.find_element(By.ID, "cart-total").click()
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > strong").click()
        self.driver.find_element(By.NAME, "search").click()
        self.driver.find_element(By.NAME, "search").send_keys("Monitors")
        self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, "p > .checkbox-inline").click()
        self.driver.find_element(By.ID, "button-search").click()
        self.driver.close()


