# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirstDemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firstDemo(self):
    self.driver.get("https://www.hollandandbarrett.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "onetrust-reject-all-handler").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .CategoryButtonsHP-module_carouselItem__FyNEN").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) .CategoryButtonsHP-module_carouselItem__p8SXL").click()
  

